### ISSUE TITLE
prplmesh-be: getall, get, set, add and del scripts

### ISSUE THREAD

**Issue by MuteSpirit** [InangoSystems/feed-mmx#16]
For make MMX WebUI and CLI for prplMesh functional and usable it's needed to write scripts for GetAll, Get, Set, Add and Delete operations in prplMesh backend.

That script must handle requests from MMX EP and interconnect with Ambiorix model of prplMesh via U-Bus

**Comment by VladyslavTupikin** [comment]
All related backends implemented, issue can be closed.
