### ISSUE TITLE
Trigger updates automatically

### ISSUE THREAD

**Issue by rmelotte** [InangoSystems/feed-mmx#43]
Currently to get information about the devices one need to follow a procedure that is not the most intuitive: 
- The "Agents" and "Interfaces" pages are initially empty, even when an agent already exist in ubus. They need to be updated manually.
- Updating the "Interfaces" page by pressing the "Update" button will have no effect: one first has to go to the "Agents" page, press the update button, then do the same for the "Interfaces" page.

This can be confusing for users who might expect the information to be available after the page finished loading. 

Maybe triggering the update automatically when the page is loaded could be considered as a first step (is it feasible? Could it have too big of an impact on the page load time?).

About the second issue, maybe it would be possible to update "parent" objects (Agents) when an object is updated (Interfaces) ?

Note that I know little of how it works internally, so I don't know what this implies.

Edit: I apparently don't have the rights to add labels, but this should have the "enhancement" label

**Comment by MuteSpirit** [comment]
Hi, Raphaël,

Thanks for your feedback.

I'd like to inform that there is another way to solve your issue - backend script may send a notification to MMX EP and trigger updating the data model (button "Update" does similar thing). As a result WebUI will show appeared and hide disappeared on web page refresh.

Such functionality is implemented in MMX core but absent in OpenSource part of MMX.

I'll escalate information about this MMX issue inside Inango.

Regards
